
#ifndef ITHADM_CAA_INC_FIXS_ITH_SNMPMIBDEFINITIONS_H_
#define ITHADM_CAA_INC_FIXS_ITH_SNMPMIBDEFINITIONS_H_


#include <stdint.h>

/* FROM NET-SNMP library
#define SNMP_OID_INTERNET		1, 3, 6, 1
#define SNMP_OID_ENTERPRISES		SNMP_OID_INTERNET, 4, 1
#define SNMP_OID_MIB2			SNMP_OID_INTERNET, 2, 1
#define SNMP_OID_SNMPV2			SNMP_OID_INTERNET, 6
#define SNMP_OID_SNMPMODULES		SNMP_OID_SNMPV2, 3
*/

#define FIXS_ITH_SNMP_OID_ERICSSON					SNMP_OID_ENTERPRISES, 193
#define FIXS_ITH_SNMP_OID_ERICSSON_AXE				FIXS_ITH_SNMP_OID_ERICSSON, 154
#define FIXS_ITH_SNMP_OID_ERICSSON_GENERIC			FIXS_ITH_SNMP_OID_ERICSSON, 177
#define FIXS_ITH_SNMP_OID_ERICSSON_ALARM			FIXS_ITH_SNMP_OID_ERICSSON, 99991



// GENERIC-SHELF-MIB notifications object OIDs for SMXB
#define FIXS_ITH_SMX_OID_SHELF_NUM									FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 1
#define FIXS_ITH_SMX_OID_SHMC_SLOT_POS								FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 2
#define FIXS_ITH_SMX_OID_SLOT_POS									FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 3
#define FIXS_ITH_SMX_OID_SHELF_MGR_STATE							FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 4
#define FIXS_ITH_SMX_OID_NEIGHBOUR									FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 5
#define FIXS_ITH_SMX_OID_CONTROL_BRD_IP_ADDRESS						FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 6
#define FIXS_ITH_SMX_OID_HW_BLADE_PRESENCE							FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 1, 7
#define FIXS_ITH_SMX_OID_BLADE_OBJECT								FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 3, 1
#define FIXS_ITH_SMX_OID_BLADE_RESET								FIXS_ITH_SMX_OID_BLADE_OBJECT, 1 ,1, 12

//TR HY52528
#define FIXS_ITH_SMX_OID_SHELF_CTRL_MGR                                                        FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 1, 2, 1, 8, 0

#define FIXS_ITH_CMX_OID_BLADE_RESET    1, 3, 6, 1, 4, 1, 193, 177, 2, 2, 2, 2, 1, 17      


// SNMPv2-MIB definitions
#define FIXS_ITH_SNMP_TRAP_OID SNMP_OID_SNMPMODULES, 1, 1, 4, 1

// SNMP_OID_MIB2 definitions                      // SMX LAG OID MIB DEFINATIONS
#define IF_ADMIN_STATUS	SNMP_OID_MIB2, 2, 2, 1, 7
#define IF_NUMBER		SNMP_OID_MIB2, 2, 1

#define SNMP_OID_IF_MIB     1, 3, 6, 1, 2, 1, 31
#define SNMP_OID_IF_NAME    SNMP_OID_IF_MIB, 1, 1, 1, 1
#define SNMP_OID_IF_HIGH_SPEED    SNMP_OID_IF_MIB, 1, 1, 1, 15

#define SNMP_LAG_MIB											   1,2,840,10006,300,43
#define IF_SPEED                                                   SNMP_OID_MIB2, 2, 2, 1, 5
#define IF_OPER_STATUS	                                           SNMP_OID_MIB2, 2, 2, 1, 8
#define IF_PHYSICAL_ADDRESS										   SNMP_OID_MIB2, 2, 2, 1, 6
#define IF_MAX_FRAME_SIZE										   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,1,2,2,1,2
#define FIXS_ITH_SMX_OID_LAG_TABLE_ENTRY                           FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,1,2,1,1,3
#define FIXS_ITH_SMX_OID_LAG_TABLE_ENTRY_IF_ALIAS 				   SNMP_OID_MIB2,31,1,1,1,18
#define FIXS_ITH_SMX_OID_LAG_GEN_IF_TYPE 						   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,1,2,1,1,2
#define FIXS_ITH_SMX_OID_LAG_GEN_IF_ROW_STATUS                     FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,1,2,1,1,3
#define FIXS_ITH_SMX_OID_LAG_PORT_ACTOR_ADMIN_KEY    			   SNMP_LAG_MIB,1,2,1,1,4
#define FIXS_ITH_SMX_OID_LAG_PORT_MODE_OF_OPERATION  			   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,2,0,6,1,2
#define FIXS_ITH_SMX_OID_LAG_PORT_ACTOR_ADMIN_STATE				   SNMP_LAG_MIB,1,2,1,1,20
#define FIXS_ITH_SMX_OID_LAG_DIST_ALGORITHM		                   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,2,0,5,1,2
#define FIXS_ITH_SMX_OID_LAG_PARTNER_PORT_ACTOR_STATE			   SNMP_LAG_MIB,1,2,1,1,23
#define FIXS_ITH_SMX_OID_LAG_MODULE                                FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,1,2,0,1,0
#define FIXS_ITH_SMX_OID_LAG_PORT_LIST_PORTS                       SNMP_LAG_MIB,1,1,2,1,1
#define SMX_LAG_FRONT_PORT1      27
#define SMX_LAG_FRONT_PORT2      28
#define SMX_LAG_VIRTUAL_PORT     37

#define FIXS_ITH_SMX_OID_USER_RESETPWD    				FIXS_ITH_SNMP_OID_ERICSSON_GENERIC,2,2,5,2,2,1,4

//SNMP OID definitions for VLAN handling

#define SNMP_DOT1DBRIDGE_MIB 							SNMP_OID_MIB2, 17, 7
#define SNMP_DOT1QVLAN_MIB								SNMP_DOT1DBRIDGE_MIB, 1, 4
#define SNMP_VLAN_MIB									SNMP_DOT1QVLAN_MIB

#define FIXS_ITH_SMX_OID_VLAN_STATIC_NAME     			SNMP_VLAN_MIB, 3, 1, 1
#define FIXS_ITH_SMX_OID_VLAN_STATIC_EGRESS_PORTS   	SNMP_VLAN_MIB, 3, 1, 2
#define FIXS_ITH_SMX_OID_VLAN_STATIC_UNTAGGED_PORTS   	SNMP_VLAN_MIB, 3, 1, 4
#define FIXS_ITH_SMX_OID_VLAN_STATIC_ROW_STATUS     	SNMP_VLAN_MIB, 3, 1, 5
#define FIXS_ITH_SMX_OID_PORTVLAN_DOT1QPVID     		SNMP_VLAN_MIB, 5, 1, 1


// AXE-ETH-SHELF-MIB definitions for TRAPs
#define FIXS_ITH_BSP_OID_TRAP_BLADE_PRESENCE        FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 0, 0, 1


#define FIXS_ITH_BSP_OID_SHELF_ID                   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 1, 2
#define FIXS_ITH_BSP_OID_SLOT_POS                   FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 1, 3
#define FIXS_ITH_BSP_OID_BLADE_ADMNSTATE            FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 2, 2, 1, 1, 3
#define FIXS_ITH_BSP_OID_BLADE_OPERSTATE            FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 2, 2, 1, 1, 4
#define FIXS_ITH_BSP_OID_BLADE_PRESENCESTATE        FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 8, 2, 2, 1, 1, 30


// SNMPv2-MIB definitions for SMX TRAPS
#define FIXS_ITH_SMX_OID_TRAP_COLD_START		    SNMP_OID_SNMPMODULES, 1, 1, 5, 1
#define FIXS_ITH_SMX_OID_TRAP_WARM_START   			FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 5, 0, 4
#define FIXS_ITH_SMX_OID_TRAP_VRRP_MASTER_CHANGE	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 11, 0, 1
#define FIXS_ITH_SMX_OID_TRAP_PIM   				FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 12, 0, 1
#define FIXS_ITH_SMX_OID_PIM_PRESENCE_STATUS		FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 12, 2, 1, 1, 2
#define FIXS_ITH_SMX_OID_PIM_MATCHING_STATUS		FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 12, 2, 1, 1, 3

#define FIXS_ITH_SMX_OID_TRAP_BFD_SESS_UP			FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 12, 0, 1
#define FIXS_ITH_SMX_OID_TRAP_BFD_SESS_DOWN			FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 12, 0, 2

#define FIXS_ITH_SMX_OID_SNMP_MIB					SNMP_OID_SNMPMODULES, 1
#define FIXS_ITH_SMX_OID_SNMP_MIB_OBJECTS	FIXS_ITH_SMX_OID_SNMP_MIB, 1
#define FIXS_ITH_SMX_OID_SNMP_MIB_TRAPS		FIXS_ITH_SMX_OID_SNMP_MIB_OBJECTS, 5

// .1.3.6.1.6.3.1.1.5.3
#define FIXS_ITH_SMX_OID_TRAP_LINK_DOWN		FIXS_ITH_SMX_OID_SNMP_MIB_TRAPS, 3

// .1.3.6.1.6.3.1.1.5.4
#define FIXS_ITH_SMX_OID_TRAP_LINK_UP			FIXS_ITH_SMX_OID_SNMP_MIB_TRAPS, 4

// SNMP-TARGET-MIB definitions for SMX Target Objects used in trap subscription request
#define FIXS_ITH_SMX_OID_TARGET_ADDR_TADDRESS						SNMP_OID_SNMPMODULES, 12, 1, 2, 1, 3
#define FIXS_ITH_SMX_OID_TARGET_TIMEOUT								SNMP_OID_SNMPMODULES, 12, 1, 2, 1, 4
#define FIXS_ITH_SMX_OID_TARGET_ADDR_TAG_LIST						SNMP_OID_SNMPMODULES, 12, 1, 2, 1, 6
#define FIXS_ITH_SMX_OID_TARGET_ADDR_PARAMS							SNMP_OID_SNMPMODULES, 12, 1, 2, 1, 7
#define FIXS_ITH_SMX_OID_TARGET_ADDR_ROW_STATUS						SNMP_OID_SNMPMODULES, 12, 1, 2, 1, 9


// BRIDGE-MIB and Q-BRIDGE-MIB definitions
#define FIXS_ITH_SMX_OID_DOT1DBRIDGE								SNMP_OID_MIB2, 17
#define FIXS_ITH_SMX_OID_BRIDGE_ADDRESS								FIXS_ITH_SMX_OID_DOT1DBRIDGE, 1, 1
#define FIXS_ITH_SMX_OID_BRIDGE_NUM_PORTS							FIXS_ITH_SMX_OID_DOT1DBRIDGE, 1, 2
#define FIXS_ITH_SMX_OID_BRIDGE_NUM_VLANS							FIXS_ITH_SMX_OID_DOT1DBRIDGE, 7, 1, 1, 4
#define FIXS_ITH_SMX_OID_BRIDGEPORT_IF_INDEX						FIXS_ITH_SMX_OID_DOT1DBRIDGE, 1, 4, 1, 2


//OID for enable/disable the Spanning Tree Protocol status of the port.
#define FIXS_ITH_SMX_OID_STP_PORT_STATUS								FIXS_ITH_SMX_OID_DOT1DBRIDGE, 2, 15, 1, 4

//RSTP_MIB
#define  FIXS_ITH_SMX_OID_STP_ADMINEDGE_PORT 						FIXS_ITH_SMX_OID_DOT1DBRIDGE, 2, 19, 1, 2

//SNMP OID definitions for SUBNET VLAN handling
#define SNMP_GEN_VLAN_MIB                       FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 8
#define SNMP_GEN_SUBNET_VLAN_ROW_STATUS    		SNMP_GEN_VLAN_MIB, 1, 2, 1, 6
#define SNMP_GEN_SUBNET_VLAN_ID         		SNMP_GEN_VLAN_MIB, 1, 2, 1, 5

//SNMP OID definitions for VRRP handling
#define SNMP_GEN_VRRP_MIB						FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 11
#define SNMP_GEN_VRRP_VRID						SNMP_GEN_VRRP_MIB, 1, 4
#define SNMP_GEN_VRRP_NEW_MASTER_ENABLE			SNMP_GEN_VRRP_MIB, 2, 1, 0

//SNMP OID definitions for BFD handling
#define SNMP_GEN_BFD_MIB							FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 12
#define SNMP_GEN_BFD_ROUTERID						SNMP_GEN_BFD_MIB, 1, 1
#define SNMP_GEN_BFD_IF_INDEX						SNMP_GEN_BFD_MIB, 1, 2
#define SNMP_GEN_BFD_SESS_DIAG						SNMP_GEN_BFD_MIB, 1, 3
#define SNMP_GEN_BFD_PEER_IP_ADDR_TYPE				SNMP_GEN_BFD_MIB, 1, 4
#define SNMP_GEN_BFD_PEER_IP_ADDR					SNMP_GEN_BFD_MIB, 1, 5
#define SNMP_GEN_BFD_UP_DOWN_NOTIFICATION_ENABLE	SNMP_GEN_BFD_MIB, 2, 1, 0

//DOT3-OAM-MIB DEFINITIONS
#define SNMP_DOT3_OAM_ADMIN_STATE			SNMP_OID_MIB2, 158, 1, 1, 1, 1

#define SNMP_GEN_IF_MIB 					FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 1, 1
#define SNMP_GEN_EXTPHY_MASTERSLAVE_STATUS	SNMP_GEN_IF_MIB,  2, 2, 1, 7

// ETHERLIKE_MIB
#define SNMP_DOT3_STATSDUPLEX_STATUS   SNMP_OID_MIB2, 10, 7, 2, 1, 19


#define SNMP_DOT3_MAU_MGT							SNMP_OID_MIB2, 26
#define SNMP_DOT3_IF_MAU_BASIC_GROUP	SNMP_DOT3_MAU_MGT, 2
#define	IF_MAU_TABLE									SNMP_DOT3_IF_MAU_BASIC_GROUP, 1
#define	IF_MAU_ENTRY									IF_MAU_TABLE, 1
#define	IF_MAU_TYPE_LIST_BITS					IF_MAU_ENTRY, 13
#define IF_MAU_DEFAULT_TYPE						IF_MAU_ENTRY, 11

#define DOT3_IF_MAU_TYPE_BASE_OID			SNMP_DOT3_MAU_MGT, 4

#define DOT3_IF_MAU_AUTO_NEG_GROUP		SNMP_DOT3_MAU_MGT, 5
#define IF_MAU_AUTO_NEG_TABLE					DOT3_IF_MAU_AUTO_NEG_GROUP, 1
#define IF_MAU_AUTO_NEG_ENTRY					IF_MAU_AUTO_NEG_TABLE, 1
#define IF_MAU_AUTO_NEG_ADMIN_STATUS	IF_MAU_AUTO_NEG_ENTRY, 1

//CMX LOG COLLECTION DEFINITIONS
#define FIXS_ITH_CMX_CONT_TRANSFER_SRV_IP	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 1, 1, 0
#define FIXS_ITH_CMX_CONT_TRANSFER_SRV_PATH	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 1, 2, 0
#define FIXS_ITH_CMX_CONT_NOTIFICATIONS_CONTROL	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 1, 3, 0
#define FIXS_ITH_CMX_CONT_AUTOMATIC_TRANSFER	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 1, 4, 0
#define FIXS_ITH_CMX_CONT_FILE_ENCRYPTION	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 1, 6, 0
#define FIXS_ITH_CMX_CONT_FILE_CREATION	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 6, 0
#define FIXS_ITH_CMX_TRANSFER_CONT_FILE	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 3, 0
#define FIXS_ITH_CMX_CONT_FILE_VALUE	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 2, 1, 0
#define FIXS_ITH_CMX_CONT_FILE_NAME	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 2, 1, 2
#define FIXS_ITH_CMX_CONT_FILE_DELETE	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 4, 4
#define FIXS_ITH_CMX_CONT_FILE_TRANSFER_COMPLETE	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 1, 2
#define FIXS_ITH_CMX_CONT_FILE_RESULT	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 2, 2, 0
#define FIXS_ITH_CMX_CONT_FILE_LEVEL	FIXS_ITH_SNMP_OID_ERICSSON_GENERIC, 2, 2, 4, 2, 3, 0

//CMX PORT PRIORITY
#define FIXS_ITH_CMX_PORT_PRIORITY 1, 3, 6, 1, 2, 1, 17, 6, 1, 2, 1, 1, 1
#define FIXS_ITH_CMX_PRIORITY 4

#define FIXS_ITH_CMX_TRAP_OID 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0

// SMX MIB objects types and constants
namespace fixs_ith_snmp {

#define SWITCH_IF_BITMAP_SIZE 29
#define SWITCH_IF_BITMAP_SIZE_CMX 26
#define IANA_LAG_IF_TYPE  161     // IANAifType == IEEE8023ad

	enum SnmpShelfSlotPosConstants {
		MIN_SHELF_SLOT_POS_LEFT = 0,
		MAX_SHELF_SLOT_POS_RIGHT = 25,
                CMX_MIN_SHELF_SLOT_POS_LEFT = 26,
                CMX_MAX_SHELF_SLOT_POS_RIGHT = 28
	};

	typedef enum SnmpPortStatusConstants {
                PORT_STATUS_UP = 1,
                PORT_STATUS_DOWN = 2,
                PORT_STATUS_TESTING = 3
	} port_status_t;

	typedef enum PimPortStatusConstants {
		        UNSUPPORTED = 0,
                ABSENT = 1,
                PRESENT = 2
	} port_presencestatus_t;

	typedef enum PimPortMatchingStatusConstants {
		        DISABLED = 0,
                MATCH = 1,
                MISMATCH = 2,
                NOTAPPLICABLE=3,
                NOMATCHING=4
	} port_matchingstatus_t;

	typedef enum SnmpOamStatusConstants {
		OAM_ADMIN_ENABLED = 1,
		OAM_ADMIN_DISABLED = 2
	} oam_status_t;

	typedef enum SnmpPortStatusType {
	                OPERATIVE_STATUS = 1,
	                ADMIN_STATUS= 2
		} status_type_t;

	typedef enum SnmpPortType {
					ETHERNETPORT = 1,
					BRIDGEPORT= 2
		} port_type_t;

	/** @brief SNMP Board Entry Field Sizes constants.
		 *
		 *	SnmpBoardDataFieldSizes enumeration detailed description
		 */
		enum SnmpBoardEntryFieldSizes {
			SNMP_MACADDRESS_FIELD_SIZE = 6
		};

	typedef enum LagEnableDisableParameter {
		        DISABLE_LAG = 0,
                ENABLE_LAG = 1,
	} lag_flag_type_t;

        typedef enum RestartTypeConstants {
                RESTART_TYPE_COLD = 0,
                RESTART_TYPE_WARM = 1,
        } restart_type_t;

	typedef enum NeighbourConstants {
			NEIGHBOUR_ABSENT = 0,
			NEIGHBOUR_PRESENT = 1
	} neighbour_t;

	typedef enum VlanPortType {
				UNTAGGED = 0,
				TAGGED = 1,
				SUBNET_BASED = 2
	} vlanPort_type_t;

   typedef uint8_t if_bitmap_t [SWITCH_IF_BITMAP_SIZE];
   typedef uint8_t if_bitmap_t_cmx [SWITCH_IF_BITMAP_SIZE_CMX];
   typedef uint8_t mac_address_t[SNMP_MACADDRESS_FIELD_SIZE];

	namespace axe {
		namespace eth {
			namespace shelf {
				typedef int32_t mag_plug_number_t;
				typedef int32_t slot_pos_t;
				typedef char ipAddress_t [4];
			}
		}
	}

	namespace qBridge {
		typedef uint32_t pvid_t;
	}

	namespace snmptarget {
		typedef enum AddrRowStatusConstants {
			 ACTIVE = 1,
			 CREATE_AND_GO = 4,
			 CREATE_AND_WAIT = 5,
			 DESTROY = 6
		} addr_row_status_t;
	}

	typedef enum stp_port_status {
		STP_PORT_ENABLED = 1,
		STP_PORT_DISABLED = 2,
	} stp_port_status_t;

	typedef enum stp_port_type {
		STP_EDGE_PORT = 1,
		STP_NOT_EDGE_PORT = 2,
	} stp_port_type_t;

	typedef enum portMasterSlaveStatus {
		PORTSTATUS_UNKNOWN = 0,
		PORTSTATUS_MASTER = 1,
		PORTSTATUS_SLAVE = 2,
		PORTSTATUS_ERROR = 3
	} portMasterSlaveStatus_t;

	typedef enum portOperatingMode {
		OPERMODE_UNKNOWN = 1,
		OPERMODE_HALFDUPLEX = 2,
		OPERMODE_FULLDUPLEX = 3
	} portOperatingMode_t;

	enum if_Mau_Auto_Neg_Admin_States {
//		FIXS_ITH_MAU_AUTO_NEG_STATUS_UNKNOWN	= 0,
		FIXS_ITH_MAU_AUTO_NEG_STATUS_ENABLED	= 1,
		FIXS_ITH_MAU_AUTO_NEG_STATUS_DISABLED	= 2
	};
}

#endif // HEADER_GUARD_FILE__fixs_ith_snmpsmcmibdefinitions
